#!/usr/bin/env python3
"""Verify asset/models/rarity.json against an independent source.

asset/gacha/cards.js is generated by scripts/generate-gacha-data.mjs straight
from the database host and carries its own `rarity` field, computed without any
of build_rarity_table.py's code.  Where the two overlap they must agree exactly;
a mismatch means one of them has the m_Rare offset wrong.

cards.js only covers gacha cards (685 of them, base + evolved forms), so it
cannot replace the table -- it can only audit it.

Exit code is non-zero on any disagreement, so this can gate a build.
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read_js_object(path: Path) -> dict:
    text = path.read_text("utf-8")
    return json.loads(text[text.index("{"):text.rindex("}") + 1])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--table", type=Path, default=ROOT / "asset/models/rarity.json")
    parser.add_argument("--cards", type=Path, default=ROOT / "asset/gacha/cards.js")
    args = parser.parse_args()

    table = json.loads(args.table.read_text("utf-8"))["models"]
    cards = read_js_object(args.cards)["cards"]

    # Both forms of a card share its rarity: evolving does not add a star, it
    # unlocks the limit break.  (That is why resource ids come in pairs.)
    expected: dict[str, int] = {}
    for card in cards:
        for key in ("resourceId", "evolvedResourceId"):
            value = card.get(key)
            if isinstance(value, int):
                expected[str(value).zfill(6)] = card["rarity"]

    shared = sorted(set(expected) & set(table))
    mismatch = [(mid, expected[mid], table[mid]["rarity"])
                for mid in shared if expected[mid] != table[mid]["rarity"]]

    print(f"cards.js resource ids: {len(expected)}   "
          f"rarity.json models: {len(table)}   overlap: {len(shared)}")
    print(f"cards.js rarity histogram: "
          f"{dict(sorted(collections.Counter(expected.values()).items()))}")
    print(f"table rarity histogram   : "
          f"{dict(sorted(collections.Counter(e['rarity'] for e in table.values()).items()))}")

    only_cards = sorted(set(expected) - set(table))
    if only_cards:
        print(f"! in cards.js but not the table: {len(only_cards)} {only_cards[:6]}")

    if mismatch:
        print(f"\nFAIL {len(mismatch)} rarity mismatches (id, cards.js, table):")
        for row in mismatch[:20]:
            print(f"  {row}")
        return 1
    print(f"\nok  all {len(shared)} shared ids agree on rarity")

    # The gate itself: no ★3 may claim a とっておき, every ★4+ must.
    bad = [(mid, e["rarity"], e["totteoki"]) for mid, e in table.items()
           if e["totteoki"] != (e["rarity"] >= 4)]
    if bad:
        print(f"FAIL {len(bad)} entries where totteoki disagrees with rarity>=4: {bad[:10]}")
        return 1
    stars3 = sum(1 for e in table.values() if e["rarity"] == 3)
    print(f"ok  gate consistent: {stars3} ★3 without a とっておき, "
          f"{len(table) - stars3} ★4+ with one")
    return 0


if __name__ == "__main__":
    sys.exit(main())
